---
"1Password": https://status.1password.com
"Cloudflare": https://www.cloudflarestatus.com
"GitHub": https://www.githubstatus.com
"OpenAI / ChatGPT": https://status.openai.com
"Anthropic / Claude": https://status.claude.com
"Vercel": https://www.vercel-status.com
"Zoom": https://status.zoom.us
"ZScaler": https://trust.zscaler.com/zscaler.net/cloud-status
"Slack": https://slack-status.com
"Replit": https://status.replit.com
